name: Test ubicloud-standard-2-ubuntu-2204

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubicloud-standard-2-ubuntu-2204

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: printenv
        run: |
          printenv
