name: Test ubuntu-2204

on:
  push:
    branches:
      - cache-test
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options: [x64, arm64]
        default: x64

jobs:
  test_image:
    uses: ./.github/workflows/test_all.yml
    with:
      runner: ubicloud-standard-2-ubuntu-2204
      image_os: ubuntu22
      arch: x64
